### ISSUE TITLE
Modifying POST request to Vindinium server

### ISSUE THREAD

**Issue by ghost** [Protoalliance/vindinium-client#10]
I am having trouble adding the map id (and optionally the number of terms) to the POST request.

Looking at `ProtoBotRunner`, it looks like `content` holds the content of the POST request which is where we would want to set the map and other information. However, bstempi has created a `UrlEncodedContent` object to hold the message, which solely consists of the API key.

I thought I could use `content.writeTo`, but this method actually writes the output of `content` to some OutputStream, which is not what we want. 

If anyone has any suggestions, let me know.

**Comment by ghost** [comment]
I think I have a better idea of how bstempi is creating the POST request. Basically, all the variables are in `ApiKey`. Right now that class only has `key` which is the API key but I am experimenting with adding a `map` field and setting its value to the appropriate map. I will post an update shortly.

**Comment by meneal** [comment]
I knocked it out.  Should I just go ahead and push it?

**Comment by meneal** [comment]
Actually adding a field to the ApiKey object won't work.  I have no idea why he was doing that.  We need to actually use this weird json object thing.

 `Map<String,String> json = new HashMap<String,String>();`
 `json.put("key", apiKey.getKey());`
 `json.put("map", "m1");`
 `content = new JsonHttpContent(JSON_FACTORY, json);`

He already had a constant set up for JSON_FACTORY.

**Comment by ghost** [comment]
Thanks for the help meneal. I was actually able to find success in modifying ApiKey, so I am testing some of the functionality and then I will push.

I am also modifying the command-line arguments and I will make a post about that when I'm done pushing.

**Comment by ghost** [comment]
I just made a push. I will post a quick summary of how to use the map parameter to the README file.
