### ISSUE TITLE
Retreating when enemy is next to a pub

### ISSUE THREAD

**Issue by ghost** [Protoalliance/vindinium-client#13]
I have noticed in a lot of these matches that sometimes our bot will engage with an enemy that is right next to a pub. This is useless if you think about it since the enemy will be able to fill its health up and you are guaranteed to die. 

Do you think it would be a good idea to check if the player you are attacking or is attacking you is next to a pub and then flee if they are?

**Comment by meneal** [comment]
I'm working on this right now in the targeting in Kronos.  I may be able to get it knocked out.

**Comment by meneal** [comment]
I think this is done.  We will see what kronos does in some later runs tomorrow.

**Comment by meneal** [comment]
This is complete in Tyr.  Closing.
