### ISSUE TITLE
Drunk Bot

### ISSUE THREAD

**Issue by meneal** [Protoalliance/vindinium-client#3]
Basic function on drunk bot is as follows:
- Target pubs
- Move to the pub
- Go in the pub repeatedly

Honestly it's a really stupid bot, but we need to have the logic to target the pubs.

**Comment by meneal** [comment]
Making a change to this to see whether it works.  I have him going to the pub no problem.  I think he can't actually get into the pub though without cash.  Humorously I'm going to make it so if he doesn't have money he wanders aimlessly, but if he has over 2 gold he rushes to the bar to get hammered again.

**Comment by ghost** [comment]
I'm sure you considered this, but I was thinking of having a condition:

if (gold >= 2)
control.finishWithSuccess()
else
control.finishWithFailure()

This would be a separate task. It looks like you have a DoIHaveCashSelector, but it consists of running to a pub and then randomly moving.

**Comment by meneal** [comment]
I actually put the check for gold in the find the closest pub task.

**Comment by meneal** [comment]
This is done.
